version: '3.8'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - database.env
    container_name: postgres-eth
    ports:
      - '5432:5432'
  
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ashok-app
    env_file: 
      - .env
    ports:
      - '4000:4000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src